version: '3.9'

services:

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  katsumiapp:
    build: ./src/KatsumiApp
    restart: always
    depends_on:
      - "rabbitmq"